--liquibase formatted sql
--changeset antoxakon:2  -- Формат: author:id
--comment: create table outbox

create table if not exists outbox_table
(
    message_id bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    payload    varchar(255) not null,
    type       varchar(255) not null
);

